services:
  - type: web
    name: jayamebel
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: FILESYSTEM_DISK
        value: r2
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_URL
        sync: false
      - key: COMPANY_NAME
        sync: false
      - key: COMPANY_ADDRESS
        sync: false
      - key: COMPANY_HOURS
        sync: false
      - key: COMPANY_WHATSAPP
        sync: false
      - key: COMPANY_PHONE
        sync: false
      - key: COMPANY_PHONE_DISPLAY
        sync: false
      - key: COMPANY_EMAIL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
